{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "bea91caa-7d93-464b-b051-2e9ee80f2b36",
   "metadata": {},
   "outputs": [],
   "source": [
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import datetime\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "\n",
    "class ASRController:\n",
    "    def __init__(self, model, view):\n",
    "        self.model = model\n",
    "        self.view = view\n",
    "\n",
    "    def add_stock(self, ticker, sector, asset_class, quantity, purchase_price):\n",
    "        self.model.add_stock(ticker, sector, asset_class, quantity, purchase_price)\n",
    "\n",
    "    def load_data(self, start, end=datetime.datetime.today().strftime('%Y-%m-%d')):\n",
    "        self.model.download_historical_data_portfolio(start, end)\n",
    "\n",
    "    def show_current_price(self, ticker):\n",
    "        return self.model.current_price(ticker)\n",
    "\n",
    "    def show_portfolio_value(self, by='asset'):\n",
    "        return self.model.portfolio_value(by=by)\n",
    "\n",
    "    def show_portfolio_weight(self, by='asset'):\n",
    "        return self.model.portfolio_weight(by=by)\n",
    "\n",
    "    def show_cumulative_return(self):\n",
    "        return_df = self.model.return_price_dataframe()\n",
    "        self.view.cumulative_return(return_df)\n",
    "\n",
    "    def show_correlation_plot(self):\n",
    "        return_df = self.model.return_price_dataframe()\n",
    "        self.view.correlation_plot(return_df)\n",
    "\n",
    "    def show_var_plot(self, confidence=0.05):\n",
    "        return_df = self.model.return_price_dataframe()\n",
    "        self.view.calculate_plot_var(return_df, confidence=confidence)\n",
    "\n",
    "    def show_portfolio_summary(self, by='asset'):\n",
    "        self.model.portfolio['Current Price'] = self.model.portfolio['Ticker'].apply(self.model.current_price)\n",
    "        self.view.portfolio_summary(self.model.portfolio, by=by)\n",
    "\n",
    "    def show_portfolio_circle(self, by='asset'):\n",
    "        self.model.portfolio['Current Price'] = self.model.portfolio['Ticker'].apply(self.model.current_price)\n",
    "        self.view.portfolio_circle_diagram(self.model.portfolio, by=by)\n",
    "\n",
    "    def simulate_and_plot_stock_paths(self, n_plot_paths=100):\n",
    "        simulations = self.model.simulate_stock_paths(number_simulations=n_plot_paths)\n",
    "        self.view.plot_simulated_paths(simulations, n_plot_paths=n_plot_paths)\n",
    "\n",
    "    def simulate_and_plot_portfolio_paths(self, mode='sample', n_plot_paths=100):\n",
    "        portfolio_paths = self.model.simulate_portfolio(number_simulations=n_plot_paths)\n",
    "        self.view.plot_simulated_portfolio_paths(portfolio_paths, mode=mode, n_plot_paths=n_plot_paths)\n",
    "    def show_var_and_cvar(self, confidence_level=0.05):\n",
    "        self.model.print_var_and_cvar(confidence_level=confidence_level)\n",
    "    def show_historical_prices(self, tickers=None, individual_graph=False):\n",
    "        close_df = self.model.close_price_dataframe()\n",
    "        self.view.plot_historical_stock_price(close_df, tickers=tickers, individual_graph=individual_graph)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62aa59c7-867b-4a6a-ad2c-c6461d54641b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
