{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "95045a38-c904-4b62-bb35-1f24b8341706",
   "metadata": {},
   "outputs": [],
   "source": [
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import datetime\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "\n",
    "class ASRModel:\n",
    "    def __init__(self):\n",
    "        self.portfolio = pd.DataFrame(columns=['Ticker', 'Sector', 'Asset Class', 'Quantity', 'Purchase Price'])\n",
    "        self.data = {}\n",
    "    def add_stock(self, ticker, sector, asset_class, quantity, purchase_price):\n",
    "        new_entry = {\n",
    "            'Ticker': ticker,\n",
    "            'Sector': sector,\n",
    "            'Asset Class': asset_class,\n",
    "            'Quantity': quantity,\n",
    "            'Purchase Price': purchase_price}\n",
    "        self.portfolio = pd.concat([self.portfolio, pd.DataFrame([new_entry])],ignore_index=True)\n",
    "    def download_historical_data_portfolio(self,start,end=datetime.datetime.today().strftime('%Y-%m-%d')):\n",
    "        tickers=self.portfolio['Ticker']\n",
    "        for ticker in tickers: \n",
    "            self.data[ticker] = yf.download(ticker,start=start,end=end)\n",
    "    def current_price(self,ticker,date=datetime.datetime.today().strftime('%Y-%m-%d')):\n",
    "        return float(self.data[ticker]['Close'].iloc[-1])\n",
    "    def close_price_dataframe(self):\n",
    "        close_df= pd.DataFrame()\n",
    "        for ticker, df in self.data.items():\n",
    "            if 'Close' in df.columns:\n",
    "                close_series=df['Close'].copy()\n",
    "                close_series.name=ticker\n",
    "                close_df=pd.concat([close_df,close_series], axis=1)\n",
    "        return close_df.dropna()\n",
    "    def return_price_dataframe(self):\n",
    "        close_df = self.close_price_dataframe()\n",
    "        return_df = close_df.pct_change().dropna()\n",
    "        return return_df\n",
    "    def calculate_expected_return(self):\n",
    "        returns_df= self.return_price_dataframe()\n",
    "        expected_returns=returns_df.mean() * 252\n",
    "        return expected_returns\n",
    "    def calculate_volatility(self):\n",
    "        returns_df= self.return_price_dataframe()\n",
    "        volatility= returns_df.std()*np.sqrt(252)\n",
    "        return volatility\n",
    "    def log_return(self):\n",
    "        close_df= self.close_price_dataframe()\n",
    "        log_returns_df= np.log(close_df/close_df.shift(1)).dropna()\n",
    "        return log_returns_df\n",
    "    def calculate_expected_log_return(self):\n",
    "        log_returns_df= self.log_return()\n",
    "        expected_log_return= log_returns_df.mean()*252\n",
    "        return expected_log_return\n",
    "    def calculate_log_volatility(self):\n",
    "        log_returns_df= self.log_return()\n",
    "        log_volatility= log_returns_df.std() * np.sqrt(252)\n",
    "        return log_volatility\n",
    "    def portfolio_value(self, by='asset'):\n",
    "        self.portfolio['Current Price'] = self.portfolio['Ticker'].apply(self.current_price)\n",
    "        self.portfolio['Market Value']= self.portfolio['Quantity'] * self.portfolio['Current Price']\n",
    "        if by == 'asset': \n",
    "            grouped= self.portfolio.groupby(\"Ticker\")['Market Value'].sum()\n",
    "        elif by == 'sector': \n",
    "            grouped= self.portfolio.groupby(\"Sector\")['Market Value'].sum()\n",
    "        elif by == 'class': \n",
    "            grouped= self.portfolio.groupby(\"Asset Class\")['Market Value'].sum()\n",
    "        else:\n",
    "            raise ValueError(\"Invalid Grouping Name choose asset , sector or class\")\n",
    "        return grouped\n",
    "    def portfolio_weight(self, by = 'asset'):\n",
    "        self.portfolio['Current Price'] = self.portfolio['Ticker'].apply(self.current_price)\n",
    "        self.portfolio['Market Value']= self.portfolio['Quantity'] * self.portfolio['Current Price']\n",
    "        \n",
    "        if by == 'asset': \n",
    "            grouped= self.portfolio.groupby(\"Ticker\")['Market Value'].sum()\n",
    "        elif by == 'sector': \n",
    "            grouped= self.portfolio.groupby(\"Sector\")['Market Value'].sum()\n",
    "        elif by == 'class': \n",
    "            grouped= self.portfolio.groupby(\"Asset Class\")['Market Value'].sum()\n",
    "        else:\n",
    "            raise ValueError(\"Invalid Grouping Name choose asset , sector or class\")\n",
    "        total = grouped.sum()\n",
    "        weights= grouped/total\n",
    "        return weights\n",
    "    def simulate_stock_paths(self,years=15,number_simulations=100000):\n",
    "        expected_returns= self.calculate_expected_log_return()\n",
    "        volatilities= self.calculate_log_volatility()\n",
    "        current_prices={ticker: self.current_price(ticker) for ticker in expected_returns.index}\n",
    "\n",
    "        dt = 1/252\n",
    "        number_of_steps= int(years*252)\n",
    "        simulations={}\n",
    "\n",
    "        for ticker in expected_returns.index:\n",
    "            mu = expected_returns[ticker]\n",
    "            sigma = volatilities[ticker]\n",
    "            S0= current_prices[ticker]\n",
    "\n",
    "            rand_matrix= np.random.normal(0,1,(number_of_steps,number_simulations))\n",
    "            price_paths= np.zeros((number_of_steps +1 , number_simulations))\n",
    "            price_paths[0]= S0\n",
    "\n",
    "            for t in range(1,number_of_steps + 1):\n",
    "                drift= (mu - 0.5 * sigma**2) * dt\n",
    "                diffusion= sigma * np.sqrt(dt) * rand_matrix[t-1]\n",
    "                price_paths[t]= price_paths[t-1] * np.exp(drift + diffusion)\n",
    "            simulations[ticker]=price_paths\n",
    "        return simulations\n",
    "    def simulate_portfolio(self,number_simulations=1000):\n",
    "        simulations= self.simulate_stock_paths(number_simulations=number_simulations)\n",
    "        weights= self.portfolio_weight(by='asset')\n",
    "        simulation_tickers= list(simulations.keys())\n",
    "        aligned_weights= weights.loc[simulation_tickers].values\n",
    "        all_prices = np.stack([simulations[ticker] for ticker in simulation_tickers], axis=-1) \n",
    "        portfolio_paths = np.sum(all_prices * aligned_weights, axis=2)\n",
    "        return portfolio_paths\n",
    "    def print_var_and_cvar(self, confidence_level=0.05):\n",
    "        portfolio_paths = self.simulate_portfolio()\n",
    "        final_values = portfolio_paths[-1, :]\n",
    "        var = np.quantile(final_values, confidence_level)\n",
    "        cvar = final_values[final_values <= var].mean()\n",
    "        print(f\"VaR {int((1 - confidence_level) * 100)}% confidence: ${var:,.2f}\")\n",
    "        print(f\"CVaR: ${cvar:,.2f}\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0cc54636-4e59-4271-af63-2efd150b4021",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
